waka:
  auth-open: true #jwt鉴权机制是否开启(true或者false)
  sign-open: true #签名机制是否开启(true或false)
  file-upload-path: /data/images/standard  #文件上传目录(不配置的话为java.io.tmpdir目录)
  rest-domain-path: https://weapp.standard.ketter.cn/

server:
  port: 8080 #项目端口
  
spring:
  profiles: daily
  datasource:
      url: jdbc:mysql://120.77.217.189:3306/ravv?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: ravv
      password: Ravv1688
      db-name: ravv_china
      filters: log4j,wall,mergeStat

logging:
  level.root: info
  level.cn.farwalker: debug
  path: logs/
  file: admin-rest.log
  
wechat:
  appid: wx0bd79a512d56a83c
  secret: 4bcc9519778c3b108822885658d5de31
  token: 111
  aesKey: wPofYpaaljbfribotOx0RfzUbGSmYN3QuoZ3JHIdDda
  msgDataFormat: JSON
  mchId: 1501826331
  mchKey: 49fd664cbf3500fd0c1d57f9b3dc20ff
  notifyUrl: https://weapp.standard.ketter.cn/wxpay/notify
#  subAppId: dsfas
#  subMchId: sdfadsf
#  keyPath: sdfsdaf

# 七牛云配置
# bucket是创建的存储空间名
# path对应存储空间的访问域名
qiniu:
  accessKey: WzBxS_J24IbwqQh3Tfh8reDLtQEsLAwQTQlxN1UM
  secretKey: EavzGisDWHA41QFeXcfS9Q1eH1b7l2ikVaXAj3Av
  bucket: standard
  path: http://idv093d.qiniudns.com