##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  waka配置  ###################
waka:
  swagger-open: true #是否开启swagger (true/false)
  kaptcha-open: false #是否开启登录时验证码 (true/false)
  file-upload-path: d:/tmp  #文件上传目录(不配置的话为java.io.tmpdir目录)
  muti-datasource-open: false #是否开启多数据源(true/false)
  spring-session-open: false #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800 #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900 #多久检测一次失效的session(只在单机环境下生效) 单位：秒

###################  项目启动端口  ###################
server:
  port: 8090


##########################################################
###################  开发环境的profile  ##################
##########################################################
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://47.107.236.246:3306/ravv_china?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: Ravv_123
    db-name: ravv
    filters: log4j,wall,mergeStat

logging:
  level.root: info
  level.cn.farwalker: debug
  path: logs/
  file: standard.log


# 七牛云配置
# bucket是创建的存储空间名
# path对应存储空间的访问域名
qiniu:
  accessKey: Mh0L0MfFlVXhgauUXh17LWEyEmIApVdwJ9QrD2Rf
  secretKey: fFydQAutvevF19DpyBs_yMY3V8oEcg2PFGMoEd6D
  bucket: ravv
  domain: http://ravv.img.shop.live